name: Discord Notifications

on: [push, pull_request, issue_comment, issues ]

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Actions Discord Webhook
        uses: nebularg/actions-discord-webhook@v1.0.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: |
            **🔔 Nova atividade no GitHub!**
            **Evento:** ${{ github.event_name }}
            **Repositório:** ${{ github.repository }}
            **Autor:** ${{ github.actor }}
            **Detalhes:** https://github.com/${{ github.repository }}
          color: "00ff00"